# Welcome to Serverless!

service: HireNow
package:
  individually: true
  exclude:
    - ./**
plugins:
  - serverless-aws-models
  - serverless-reqvalidator-plugin
  - serverless-aws-documentation
  - serverless-iam-roles-per-function
  - serverless-dynamodb-local
provider:
  name: aws
  runtime: python3.8
  apiName: ${self:service}Api
  description: App to automate hiring process

# you can overwrite defaults here
#  stage: dev
  region: ap-south-1
  # environment:
  #   myTable: ${self:custom.myTable}
  iamRoleStatements:
      - Effect: "Allow"
        Action:
          - cloudwatchlogs:*
          - dynamodb:*
        Resource: "*"

functions:
  - ${file(services/post-job/job.yml)}

custom:
  studentsTable: 'post_job'
  models:
    PostJobRequest:
      ContentType: "application/json"
      Schema: ${file(services/post-job/post-job-req.json)}

resources:
    - ${file(./resources/onlyBody.yml)}
    - ${file(./resources/dynamodb.yml)}
